import { Inter } from "next/font/google";
import "../../globals.css";
import DashboardSidebar from "@/components/DashboardSidebar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { redirect } from "@/navigation";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default async function DashboardLayout({ children }) {
  // Single server-side enforcement point for the whole dashboard: role is
  // derived from the session, never trusted from the client.
  const session = await getServerSession(authOptions);
  if (!session || session.user?.role !== "admin") {
    redirect("/login");
  }
  return (
    <DashboardSidebar>
      <main>{children}</main>
    </DashboardSidebar>
  );
}
