import { Inter } from "next/font/google";
import "../../globals.css";
import DashboardSidebar from "@/components/DashboardSidebar";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};
export default function DashboardLayout({ children }) {
  return (
    <DashboardSidebar>
        <main>{children}</main>
    </DashboardSidebar>
  );
}
