import { Inter } from "next/font/google";
import ".././globals.css";
import { NextIntlClientProvider, useMessages } from 'next-intl';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale }
}) {
  const messages = useMessages();
  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider></body>
    </html>
  );
}
